game_config:
  "game_path": "Crawler_Linux",
  "unity_file": "Crawler.x86_64",
  "agent": "ddpg"


agent_config:
  "LR_ACTOR": 1e-4,
  "LR_CRITIC": 1e-4,
  "CRITIC_COUNT": 2,
  "WEIGHT_DECAY": 1e-6,
  "UPDATE_EVERY": 2,
  "POLICY_DELAY": 2,
  "BUFFER_SIZE": 1e6,
  "BATCH_SIZE": 512,
  "GAMMA": 0.99,
  "TAU": 1e-3,
  "ACTION_MIN": -1.0,
  "ACTION_MAX": 1.0,
  "CLIP_ACTOR_GRADIENTS": False,
  "CLIP_CRITIC_GRADIENTS": False,
  "MEMORY_MODULE": "NaivePrioritizedBuffer"
